-
  hosts: docker
  tasks:
    - name: Update apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt and repository over HTTPS
      become: yes
      apt:
        name: "{{packagesdep}}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - git
        - apt-transport-https
        - ca-certificates
        - wget
        - software-properties-common
        - gnupg2
        - curl

    - name: Add apt singing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker official repository for Debian Stretch
      become: yes
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/debian {{ansible_lsb.codename}} stable
        state: present

    - name: Index new repo into tje cache
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: actually install docker
      become: yes
      apt:
        name: "docker-ce"
        state: latest